name: 'Infrastructure CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        id: init
        run: terraform init

      - name: 'Terraform Validate'
        id: validate
        run: terraform validate

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-validate

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        id: init
        run: terraform init

      - name: 'Terraform Apply'
        id: apply
        run: terraform apply -auto-approve
